language: node_js
node_js:
- '4'
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_1d8c928d4920_key -iv $encrypted_1d8c928d4920_iv
  -in .travis/secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- cp .keystore ~/.keystore
install:
- curl https://install.meteor.com | /bin/sh
- npm install
- npm install -g meteor-launch
- wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
- tar zxvf android-sdk_r24.4.1-linux.tgz > /dev/null
- mv android-sdk-linux .android
- export ANDROID_HOME="$TRAVIS_BUILD_DIR/.android"
- echo y | .android/tools/android update sdk --no-ui --all --filter tools,platform-tools,build-tools-23.0.3,android-23,extra-android-m2repository,extra-google-m2repository
- export ANDROID_ZIPALIGN="$TRAVIS_BUILD_DIR/.android/build-tools/23.0.3/zipalign"
- sudo apt-get install lib32z1 libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5
script:
- launch build launch-crosswalk-example.herokuapp.com
- ./.build/android/project/cordova/build --release
- mv ./.build/android/project/build/outputs/apk/project-armv7-release-unsigned.apk ./.build/android/project/build/outputs/apk/android-armv7-release-unsigned.apk
- mv ./.build/android/project/build/outputs/apk/project-x86-release-unsigned.apk ./.build/android/project/build/outputs/apk/android-x86-release-unsigned.apk
- ls -al .build
- ls -al .build/android
- ls -al .build/android/project
- ls -al .build/android/project/build
- ls -al .build/android/project/build/outputs
- ls -al .build/android/project/build/outputs/apk
- launch hockey
deploy:
  provider: heroku
  api_key:
    secure: iIS2YQksdO/MHXKztgA7td6pQuo2j54hn+8TGV44t75G177yxJOpI7mLyQ8mMFQHSrIlRyW47eCej6h/iN/711B8W8qFYdV3/UO3K1QSz26xg5VFk2Cy0pb1GxNNkuiLEj0lTkS8bImuSKCzau4lGNkF/V1gvNTinDRQhVa8BIsVy2ZhJuLdRDxIP0Y6PCb2hrrjor4qocZmNXBZuKwUyxAwv65Bgx34aHeO/Bpth2fQu+j9nBLPbrGkQUqLVQKcx7PpfbGkcYKprQdML6edE7QulPjD0mjVNn7GI1XOoVPfj8/6ttIb3fWlAxpF9kWitbeBZqD44TXHTcM3yvNVAKz5z3GsvYxpwbtu7/g3UHDxy51u/hVj0tEpHJg65z+GMAAbwj3ymtYY5eUeUKbSnmaRJ15qvyFxa3MlHKpwqBubzh9++zFenyPyCWc8QXgCPwu292ULwj/acfdWoOa/8Ctkikde1qYNKE0WNhGmB89ZFmCHZe+ghOCXWoXzaHgTya7k7jDPA7XO4wZMBV+MuaNGALgv3ExFx6UBolllk6IkEBrSIDh18G6ATjxtAVoKNzi1ggvg9wZedtjXEsEQMJFaMPHeSVi9A3pSZmCtvWZBcc2COfpy1LdodIyLJE+yIwfcyw3J+rgzeVB8UPueLP2MkRGD8X5dQ9YodQLe6ig=
  app: launch-crosswalk-example
  on:
    repo: NewSpring/launch-crosswalk-example
